# Required metadata – Basic information about the project
sonar.projectKey=frag.jetzt-frontend
sonar.projectName=frag.jetzt Frontend
sonar.projectVersion=3.0

# Primary language of the project (TypeScript)
sonar.language=ts

# Directory containing the source code to analyze
sonar.sources=src

# Patterns for files to exclude from analysis
sonar.exclusions=dist/**/*, node_modules/**/*, **/*.spec.ts

# Character encoding of the source files
sonar.sourceEncoding=UTF-8

# Directory containing test files
sonar.tests=src

# Pattern to identify test files within the project
sonar.test.inclusions=**/*.spec.ts

# Path to the test coverage report
sonar.typescript.lcov.reportPaths=coverage/lcov.info

# URL of the SonarQube server
sonar.host.url=http://sonarqube:9000

# Ignore all deprecated warnings across the entire project
sonar.issue.ignore.multicriteria=1,2

# Rule ID for '@deprecated' annotation warnings
sonar.issue.ignore.multicriteria.1.ruleKey=typescript:S1133
# Apply to all files in the project (global pattern)
sonar.issue.ignore.multicriteria.1.resourceKey=**

# Rule ID for using deprecated code warnings
sonar.issue.ignore.multicriteria.2.ruleKey=typescript:S1874
# Apply to all files in the project (global pattern)
sonar.issue.ignore.multicriteria.2.resourceKey=**
