@startuml

skinparam Padding 5
skinparam backgroundColor #EEEBDC

legend right
  |<img:https://git.thm.de/arsnova/frag.jetzt/-/raw/staging/src/assets/icons/android-chrome-192x192.png> |= \n\n »frag.jetzt« |
  | Production | [[https://frag.jetzt]] |
  | Repository | [[https://git.thm.de/arsnova/frag.jetzt]] |
  | Staging Server | [[https://staging.frag.jetzt]] |
  | UML-Tool| PlantUML v1.2022.1|
  | Diagramtype | Class Diagram |
  | Creator| Ruben Bimberg |
  | Mail| ruben.bimberg@mni.thm.de |
  | Last Changed| 19.02.2022 |
end legend

@enduml
