@startuml

scale 1.0

left to right direction

skinparam backgroundColor Linen
skinparam LegendBackgroundColor Strategy
skinparam LegendBorderThickness 0
skinparam LegendFontSize 20
skinparam Padding 5
skinparam defaultFontSize 24
skinparam Nodesep 100
skinparam ArrowThickness 2
skinparam shadowing true

skinparam usecase {
    BackgroundColor PaleGreen
    BorderColor Green
    BackgroundColor<<USP>> Pink
    BorderColor<<USP>> HotPink
    BorderThickness 2
    ArrowThickness 2
    ArrowColor Green
    ActorBorderColor Green
}

actor Lecturer
actor Student
actor Moderator

note "If a lecturer is registered and logs in with her account, \nher sessions remain stored for 180 days after the last visit, \notherwise they are deleted when she logs out." as NoteForCreateSession
note "Registered students can receive a bonus \nfor particularly interesting questions." as NoteForJoinSessionAsStudent
note "as another option we have general, fond, hover and \nweight-classes that apply to the sight of the cloud " as NoteForDemoCloud
note "it is possible to choose the language for the spelling." as NoteForSpellCheck

rectangle "frag.jetzt | use-case diagram \n" << Business >> {

    (Create session) --- NoteForCreateSession
    (Join session as student) --- NoteForJoinSessionAsStudent
    (Demo cloud) --- NoteForDemoCloud
    (My cloud) - NoteForDemoCloud
    (Spell check) -- NoteForSpellCheck

    Lecturer -- (Create session)
    (Evaluate questions) <.. (Delete question) : << extend >>
    Student-- (Join session as student)
    Moderator ---- (Join session as Moderator)
    (Join session as Moderator)<..(Moderate questions): << extend >>
    (Create session) <.. (Question wall) : << extend >>
    (Create session) <.. (Question wall) : << extend >>
    (Create session) <.. (Edit session) : << extend >>
    (Create session) <.. (Evaluate questions) : << extend >>
    (Create session) <.. (Assign moderator to session) : << extend >>
    (Create session) <.. (Create question tag) : << extend >>
    (Create session) <.. (Export questions) : << extend >>
    (Create session) <.. (Ask question) : << extend >>
    (Create session) <.. (Rate questions) : << extend >>
    (Create session) <.. (Redeem bonus token) : << extend >>
    (Create session) <.. (Evaluate questions) : << extend >>
    (Create session) <.. (Block question) : << extend >>
    (Create session) <.. (Add keyword) : << extend >>
    (Create session) <.. (Topic cloud) : << extend >>
    (Create session) <.. (Question focus) : << extend >>


    (Moderate questions) <.. (Ban question) : << extend >>
    (Evaluate questions) <.. (Ban question) : << extend >>
    (Join session as student) <.. (Question wall) : << extend >>
    (Join session as student) <.. (Ask question) : << extend >>
    (Join session as student) <.. (Vote up question) : << extend >>
    (Join session as student) <.. (Vote down question) : << extend >>
    (Join session as student) <.. (Export questions) : << extend >>
    (Join session as student) <.. (Add keyword) : << extend >>
    (Join session as student) <.. (Topic cloud) : << extend >>
    (Join session as student) <.. (Question focus) : << extend >>



    (Join session as Moderator) <.. (Ask question) : << extend >>
    (Join session as Moderator) <.. (Block question) : << extend >>
    (Join session as Moderator) <.. (Rate questions) : << extend >>
    (Join session as Moderator) <.. (Export questions) : << extend >>
    (Join session as Moderator) <.. (Add keyword) : << extend >>
    (Join session as Moderator) <.. (Question wall) : << extend >>
    (Join session as Moderator) <.. (Topic cloud) : << extend >>
    (Join session as Moderator) <.. (Question focus) : << extend >>
    (Ask question) <.. (Spell check) : << extend >>
    (Ask question) <.. (Add keyword) : << extend >>
    (Ask question) <.. (Publish question) : << extend >>
    (Create check) <.. (Correct Spelling) : << extend >>

    (Question wall) <.. (Filter) : << extend >>
    (Evaluate questions) <.. (Tag) : << extend >>
    (Evaluate questions) <.. (Delete) : << extend >>
    (Evaluate questions) <.. (Mark as wrong) : << extend >>
    (Evaluate questions) <.. (Mark as true) : << extend >>
    (Evaluate questions) <.. (Republish) : << extend >>
    (Evaluate questions) <.. (Answer) : << extend >>
    (Evaluate questions) <.. (Star) : << extend >>
    (Evaluate questions) <.. (Ban question) : << extend >>
    (Topic cloud) <.. (Edit topic cloud) : << extend >>
    (Topic cloud) <.. (Edit cloud view) : << extend >>
    (Edit cloud view) <.. (My cloud) : << extend >>
    (Edit cloud view) <.. (Demo cloud) : << extend >>
    (Topic cloud) <.. (Correct a keyword) : << extend >>
    (Moderate questions) <.. (Tag) : << extend >>
    (Moderate questions) <.. (Bookmark) : << extend >>
    (Moderate questions) <.. (Delete) : << extend >>
    (Moderate questions) <.. (Mark as wrong) : << extend >>
    (Moderate questions) <.. (Mark as true) : << extend >>
    (Moderate questions) <.. (Republish) : << extend >>
    (Moderate questions) <.. (Answer) : << extend >>
    (Moderate questions) <.. (Star) : << extend >>
    (Moderate questions) <.. (Ban question) : << extend >>
    (Moderate questions) <.. (Bookmark) : << extend >>
    (Question focus) <.. (Filter) : << extend >>

}

legend right
  |<img:https://git.thm.de/arsnova/arsnova-lite/raw/staging/src/assets/icons/Logo_frag_jetzt_128x128.png> |= \n\n »frag.jetzt« |
  | Produktion | [[https://frag.jetzt]] |
  | Repository | [[https://git.thm.de/arsnova/frag.jetzt]] |
  | Staging Server | [[https://staging.frag.jetzt]] |
  | UML-Tool| PlantUML v5.5.1|
  | Ersteller| Kevin Piam , Franck Mezatio |
  | Letzte Änderung| 20.06.2021 |
end legend

@enduml
