export { demoMap };
const demoMap = new Map<string, number>();
      demoMap.set("Topic 1",1);
      demoMap.set("Topic 2 of 1",1);
      demoMap.set("Topic 3 of 1",1);
      demoMap.set("Topic 4 of 1",1);
      demoMap.set("Topic 5 of 1",1);
      demoMap.set("Topic 6 of 1",1);
      demoMap.set("Topic 7 of 1",1);
      demoMap.set("Topic 8 of 1",1);
      demoMap.set("Topic 9 of 1",1);
      demoMap.set("Topic 10 of 1",1);
      demoMap.set("Topic 2",2);
      demoMap.set("Topic 2 of 2",2);
      demoMap.set("Topic 3 of 2",2);
      demoMap.set("Topic 4 of 2",2);
      demoMap.set("Topic 5 of 2",2);
      demoMap.set("Topic 6 of 2",2);
      demoMap.set("Topic 7 of 2",2);
      demoMap.set("Topic 8 of 2",2);
      demoMap.set("Topic 9 of 2",2);
      demoMap.set("Topic 3",3);
      demoMap.set("Topic 2 of 3",3);
      demoMap.set("Topic 3 of 3",3);
      demoMap.set("Topic 4 of 3",3);
      demoMap.set("Topic 5 of 3",3);
      demoMap.set("Topic 6 of 3",3);
      demoMap.set("Topic 7 of 3",3);
      demoMap.set("Topic 8 of 3",3);
      demoMap.set("Topic 4",4);
      demoMap.set("Topic 2 of 4",4);
      demoMap.set("Topic 3 of 4",4);
      demoMap.set("Topic 4 of 4",4);
      demoMap.set("Topic 5 of 4",4);
      demoMap.set("Topic 6 of 4",4);
      demoMap.set("Topic 7 of 4",4);
      demoMap.set("Topic 5",5);
      demoMap.set("Topic 2 of 5",5);
      demoMap.set("Topic 3 of 5",5);
      demoMap.set("Topic 4 of 5",5);
      demoMap.set("Topic 5 of 5",5);
      demoMap.set("Topic 6 of 5",5);
      demoMap.set("Topic 6",6);
      demoMap.set("Topic 2 of 6",6);
      demoMap.set("Topic 3 of 6",6);
      demoMap.set("Topic 4 of 6",6);
      demoMap.set("Topic 5 of 6",6);
      demoMap.set("Topic 7",7);
      demoMap.set("Topic 2 of 7",7);
      demoMap.set("Topic 3 of 7",7);
      demoMap.set("Topic 4 of 7",7);
      demoMap.set("Topic 8",8);
      demoMap.set("Topic 2 of 8",8);
      demoMap.set("Topic 3 of 8",8);
      demoMap.set("Topic 9",9);
      demoMap.set("Topic 2 of 9",9);
      demoMap.set("Topic 10",10);