@startuml Bonus awarding
title frag.jetzt | PLE Workflow

skinparam backgroundColor Linen
skinparam shadowing true
skinparam defaultFontSize 14
skinparam Padding 6

|#CE93D8|Learner|

partition "Create a Study room" {

  start

  :go to frag.jetzt;
  if(Study room already exists?) then (yes)
    :go to the Study room;
  else (no)
    :Click on "Create a room";
    :Enable or disable AI;
    :Choose Student as role;
    :Enter a room name;
    :Create a room by clicking "Create a room";
  endif
  stop
}

|#90CAF9|Co-Learner|

partition "Join Study room" {
  start
  :go to frag.jetzt;
  floating note left: The Learner has given you the key code.
  if(you have an account?) then (yes)
    :sign in;
    :go to the Study room;
  else (no)
    :join Study room as guest;
  endif
  stop
}

partition "Create topics" {
  start
  floating note left: You are in an owned study room with AI enabled.
  :go to »Topic board«;
  (T)
  :open editor;
  :write topic;
  :post topic board;
  if (want to ask more topics?) then (yes)
    (T)
    detach
  else (no)
    stop
  endif
}

|Learner|

partition "Setup Rooms AI Assistant" {
  start
  floating note left: While you are in a study room.
  :go to »AI Assistant«;
  if (you have already created Assistant?) then (yes)
    :Select default AI Assistant;
    stop
  else (no)
    :create AI Assistant;
  endif

  (T)
  fork
    :Enter required information;
  fork again
    :Abort creation;
    if (Was some data entered?) then (yes)
      :Confirm abort;
      if (Abort confirmed?) then (yes)
        stop
      else (no)
        (t)
        detach
      endif
    endif
  fork again
    if (Was adding of AI Assistant requested?) then (yes)
      if (All required information is provided?) then (no)
        (t)
        detach
      endif
      if (Given information is valid?) then (no)
        (t)
        detach
      endif
      :Save and set new AI Assistant as default;
      stop
    else (no)
      (T)
      detach
    endif
  end fork
  (T)
  detach
}

partition "Edit existing Room AI Assistants" {
  start
  floating note left: You are in an owned study room with AI enabled.
  :go to »AI Assistant«;
  :Click on "Create AI Assistant";
  :Click "Edit" on the Assistant you want to change;
  (T)
  fork
    :Enter required information;
  fork again
    :Abort creation;
    if (Was some data entered?) then (yes)
      :Confirm abort;
      if (Abort confirmed?) then (yes)
        stop
      else (no)
        (t)
        detach
      endif
    endif
  fork again
    if (Was adding of AI Assistant requested?) then (yes)
      if (All required information is provided?) then (no)
        (t)
        detach
      endif
      if (Given information is valid?) then (no)
        (t)
        detach
      endif
      :Save and set edited AI Assistant as default;
      stop
    else (no)
      (T)
      detach
    endif
  end fork
  (T)
  detach
}

partition "Delete existing Room AI Assistants" {
  start
  floating note left: You are in an owned study room with AI enabled.
  :go to »AI Assistant«;
  :Click on "Create AI Assistant";
  :Click "Delete" on the Assistant you want to delete;
  stop
}

|Co-Learner|

partition "Answer question via Room AI Assistant" {
  start
  floating note left: While you are in a study room.
  :Go to »Q&A board«;
  :Select a Question;
  :Press "Send to AI";
  (D)
  if (Want to answere the question by rooms default AI Assistant?) then (no)
    :Choose select one alternative Assistant from "Assistant" menu;
  endif
  :Submit question to AI by clicking "Send";
  if (Want to deepen the conversation?) then (yes)
    :Ask the AI some follow up questions;
    (D)
    detach
  else (no)
    stop
  endif
}

partition "Start new Chat with Room AI Assistant" {
  start
  floating note left: While you are in a study room with an AI Assistant.
  :Go to »AI Assistant«;
  :Enter your question in the chat textfield;
  (D)
  if (Want to answere the question by rooms default AI Assistant?) then (no)
    :Choose select one alternative Assistant from "Assistant" menu;
  endif
  :Submit question to AI by clicking "Send";
  if (Want to deepen the conversation?) then (yes)
    :Ask the AI some follow up questions;
    (D)
    detach
  else (no)
    stop
  endif
}

|Learner|

partition "Chat with Platform AI Assistant" {
  start
  floating note left: While you are in the room overview.
  :Press "AI Assistant" in navigation menu;
  :Enter your question in the chat textfield;
  :Submit the question to AI by clicking "Send";
  (D)
  if (Want to deepen the conversation?) then (yes)
    :Ask the AI some follow up questions;
    (D)
    detach
  else (no)
    stop
  endif
}

legend right
|<img:https://git.thm.de/arsnova/frag.jetzt/-/raw/staging/src/assets/icons/chat_bot_green.png{scale=0.4}> |= \n\n »frag.jetzt« |
| Domain glossary | [[https://git.thm.de/arsnova/frag.jetzt/-/raw/staging/docs/diagrams/Glossary.pdf]] |
| Production server | [[https://frag.jetzt]] |
| Repository | [[https://git.thm.de/arsnova/frag.jetzt/-/blob/staging/README.md]] |
| Staging server | [[https://staging.frag.jetzt]] |
| UML tool| PlantUML-Server Version 1.2023.12 - graphviz (20230911.1827)|
| Authors| Ruben Bimberg, Klaus Quibeldey-Cirkel, Sascha San Juan|
| Contact| [[mailto:ruben.bimberg@mni.thm.de]] |
| Last revision| 23.12.2024 |
end legend
