@startuml
title frag.jetzt | Workflow for Bonus awarding

skinparam backgroundColor Linen
skinparam shadowing true
skinparam defaultFontSize 14
skinparam Padding 6

|#CE93D8|Lecturer|

start

:go to frag.jetzt;
if(lecturer has an account?) then (yes)
    :login;
    if(room already exists?) then (yes)
        :access room;
    else (no)
        :create room;
    endif
else (no)
    :login as guest;
    :create room;
endif

fork
    :wait for questions;
fork again
partition "Share room" {
    :give students and moderators 
    the opportunity to access room;
}

|#90CAF9|Student|

fork
    :go to frag.jetzt;
    if(participant has an account?) then (yes)
        :login;
        :access room;
    else (no)
        :access room as guest;
    endif
    :go to »Q&A forum«;
    partition "Ask a question" {
    repeat
        :open editor;
        :write question;
        :post question;
    repeat while (want to ask more questions?)
    }

fork again
    |#FFAF49|Moderator|
    :go to frag.jetzt;
    :login;
    :access room;
    |Student|
end fork
|Lecturer|
end fork

if (proceed according to role) then (lecturer)
    :go to »Q&A forum«;
    
    partition "Mark question" {
    (A)
    :review question;
    if(question is particularly good?) then (yes)
        :mark question with a star;
    else (no)
        if(unreviewed questions exist?) then (yes)
           (A)
           detach
        else (no)
            stop
        endif
    endif
    }
    else (moderator)
        |Moderator|
        :go to »Q&A forum«;
        partition "Mark question" {
        (B)
        :review question;
        if(question is particularly good?) then (yes)
            :mark question with a star;
        else (no)
            if(unreviewed questions exist?) then (yes)
               (B)
               detach
            else (no)
                stop
            endif
        endif
        }
endif


|Student|

partition "Redeem bonus code" {
:select »My rooms«;
:select »My bonus stars«;
:choose a room;
:redeem token;
:send mail with token to lecturer;
}

|Lecturer|

partition "Award bonus points" {
:receive email with token from student;
:navigate to »Room management«;
:select »Bonus archive«;
:check the validity of token";
if(token from email and token in 
bonus archive are identical?) then (yes)
    :review question again;
    if(question is worth bonus points?) then (yes)
        :award student bonus points;
    else (no)
        :send email back with answer;
        stop
    endif
else (no)
    stop
endif
Stop
}


legend right
  |<img:https://git.thm.de/arsnova/frag.jetzt/-/raw/staging/src/assets/icons/Logo_frag_jetzt_128x128.png> |= \n\n »frag.jetzt« |
  | Domain-Glossar | [[https://git.thm.de/arsnova/frag.jetzt/-/blob/staging/docs/diagrams/Glossary.pdf]] |
  | Produktion | [[https://frag.jetzt]] |
  | Repository | [[https://git.thm.de/arsnova/frag.jetzt]] |
  | Staging Server | [[https://staging.frag.jetzt]] |
  | UML-Tool| PlantUML-Server Version 1202202|
  | Ersteller| Tim Lennard Debre|
  | Letzter Bearbeiter| Klaus Quibeldey-Cirkel|
  | Kontakt| [[mailto:klaus.quibeldey-cirkel@mni.thm.de]] |
  | Erstellt| 09.01.2021 |
  | Letzte Überarbeitung| 29.11.2022 |
end legend
@enduml