@startuml Use Cases
scale 1.0

skinparam backgroundColor Linen
skinparam LegendBackgroundColor Strategy
skinparam LegendBorderThickness 0
skinparam LegendFontSize 12
skinparam Padding 5
skinparam defaultFontSize 14
skinparam ArrowThickness 2
skinparam shadowing true

!$stringList = ""

!procedure $append($value)
  !if %strlen($stringList) > 0
    !$stringList = $stringList + "\n" + $value
  !else
    !$stringList = $value
  !endif
!endprocedure

!procedure $print()
  !$i = %strpos($stringList, "\n")
  !while $i > 0
    !$arg = %substr($stringList, 0, $i)
    $arg
    !$stringList = %substr($stringList, $i + 2)
    !$i = %strpos($stringList, "\n")
  !endwhile
  !if %strlen($stringList) > 0
  $stringList
  !endif
!endprocedure

!procedure $GUUseCase($id, $data)
  ($data) as ($id) #linen;line:black;line.bold;text:black
  $append(GU + "-->" + $id)
!endprocedure

!procedure $CLUseCase($id, $data)
  ($data) as ($id) #lightgreen;line:black;line.bold;text:black
  $append(CL + "-->" + $id)
!endprocedure

!procedure $LUseCase($id, $data)
  ($data) as ($id) #lightblue;line:black;line.bold;text:blue
  $append(L + "-->" + $id)
!endprocedure

!procedure $RUUseCase($id, $data)
  ($data) as ($id) #pink;line:black;line.bold;text:black
  $append(RU + "-->" + $id)
!endprocedure

!procedure $UseCase($id, $data)
  ($data) as ($id)
!endprocedure

!procedure $Includes($uc1, $uc2)
  $append($uc1 + "-.-> " + $uc2 + " : <<includes>>")
!endprocedure

skinparam rectangle {
  BackgroundColor #fdf6e0
}

skinparam usecase {
  BorderThickness 2
  ArrowThickness 2
}

rectangle "PLE Use Case Diagram" {

  left to right direction

  actor "Guest User" as GU #linen;line:black;line.bold;text:black
  actor "Co-Learner" as CL #lightgreen;line:green;line.bold;text:green
  actor "Learner" as L #LightBlue;line:blue;line.bold;text:blue
  actor "Registered User" as RU #pink;line:red;line.bold;text:red

  CL -left-|> GU
  RU -left-|> CL
  L -left-|> RU

  rectangle "frag.jetzt" <<webService>> {
    together {
      $GUUseCase(UC1, "Switch between PLE and ARS")
      $GUUseCase(UC2, "Book a study room\nfor a maximum of 180 days\nwithout AI assistant")
      $GUUseCase(UC3, "Join a Study room")
      $GUUseCase(UC4, "Create an Account")
      $GUUseCase(UC5, "Login as Registered User")
      $GUUseCase(UC6, "Logout of Account")
      $GUUseCase(UC7, "Choose between\nGerman, Englisch and French\nas UI language")
      $GUUseCase(UC8, "Change the color theme of the platform")
      $UseCase(UC9, "«USP»\nChat with study room AI assistant")
      UC3 .> UC9 : <<extends>>
      $UseCase(UC10, "«USP»\nChat with specialized AI assistant")
      UC10 .> UC9 : <<extends>>
    }

    note right of (UC10)
      «preCondition»
      Study room provides specialized AI assistants
    end note

    note right of (UC6)
      «preCondition»
      User is logged in.
      «postCondition»
      User is logged out.
    end note

    note right of (UC1)
      «postCondition»
      When switching from PLE to ARS, the user is redirected to the ARS section.
      When switching from ARS to PLE, the user is redirected to the PLE section. (This diagram)
    end note

    note right of (UC2)
      «postCondition»
      Guest User becomes a Learner.
    end note

    note right of (UC3)
      «postCondition»
      Guest User becomes a Learner.
    end note

    note right of (UC4)
      «postCondition»
      Guest User becomes a Registered User.
    end note

    note right of (UC9)
      «preCondition»
      Study room has AI assistants enabled"
    end note

    together {
      $CLUseCase(UC11, "Create a Topic in Q&A Forum")
      $CLUseCase(UC12, "«USP»\nAnswer Topics in Q&A Forum\nwith room AI assistants")
      $CLUseCase(UC13, "Answer Topics in Q&A Forum")
      $CLUseCase(UC14, "«USP»\nUse Radar-Mode\nto analyse Answers of a Topic\nwith AI")
    }

    note right of (UC12)
      «preCondition»
      Study room has AI assistants enabled.
    end note

    rectangle "Manage Room AI assistants" {
      $UseCase(UC15, "Manage AI assistants")
      $UseCase(UC16, "Enable AI assistant")
      $Includes(UC15, UC16)
      $UseCase(UC17, "Disable AI assistant")
      $Includes(UC15, UC17)
      $UseCase(UC18, "Create specialized AI assistant")
      $Includes(UC15, UC18)
      $UseCase(UC19, "Remove specialized AI assistant")
      $Includes(UC15, UC19)
      $UseCase(UC20, "Set default room AI assistant")
      $Includes(UC15, UC20)
    }

    note bottom of (UC15)
      «preCondition»
      Room has AI assistants enabled.
    end note

    rectangle "Manage Personal AI assistants" {
      $RUUseCase(UC21, "Manage personal AI assistant")
      $UseCase(UC22, "Manage quota of AI assistant")
      $Includes(UC21, UC22)
      $UseCase(UC23, "Select AI model for AI assistant")
      $Includes(UC21, UC23)
    }

    together {
      $RUUseCase(UC24, "Book a study room for at least 180 days")
      $RUUseCase(UC25, "Get free access to ChatGPT")
      $RUUseCase(UC26, "Delete Account")
    }

    note right of (UC26)
      «postCondition»
      All data associated with the account is deleted
      and the account is removed from the system.
    end note

    note right of (UC24)
      «postCondition»
      Registered User becomes a Learner.
    end note

    together {
      $LUseCase(UC27, "Manage study room")
    }

    UC27 <-.- UC15 : <<extends>>
    $UseCase(UC28, "Conduct a brainstorming session")
    UC27 <-.- UC28 : <<extends>>
    $UseCase(UC29, "Generate Ideas from AI")
    UC28 <-.- UC29 : <<extends>>

    note right of (UC29)
      «preCondition»
      Study room has AI assistants enabled.
    end note

    note right of (UC25)
      «preCondition»
      The platform has the global ChatGPT enabled"
    end note

  $print()
}

legend right
|<img:https://git.thm.de/arsnova/frag.jetzt/-/raw/staging/src/assets/icons/chat_bot_green.png{scale=0.4}> |= \n\n »frag.jetzt« — PLE mode|
| Domain glossary | [[https://git.thm.de/arsnova/frag.jetzt/-/raw/staging/docs/diagrams/Glossary.pdf]] |
| Production server | [[https://frag.jetzt]] |
| Repository | [[https://git.thm.de/arsnova/frag.jetzt/-/blob/staging/README.md]] |
| Staging server | [[https://staging.frag.jetzt]] |
| UML tool| PlantUML-Server Version 1.2024.3 - graphviz (20230911.1827)|
| Authors| Ruben Bimberg, Klaus Quibeldey-Cirkel, Sascha San Juan|
| Contact| [[mailto:ruben.bimberg@mni.thm.de]] |
| Last revision| 23.12.2024 |
end legend
@enduml
