@startuml Domain diagram
skinparam class {
  BackgroundColor PaleGreen
  BorderColor Green
  ArrowColor black
  FontSize 28
  BackgroundColor<<webService>> yellow
  BorderColor<<webService>> orange
}

skinparam backgroundColor Linen
skinparam linetype ortho
skinparam shadowing true
skinparam minClassWidth 200
skinparam ArrowThickness 1
skinparam LegendBackgroundColor Strategy
skinparam LegendBorderThickness 0
skinparam LegendFontSize 20
skinparam defaultFontSize 20
skinparam Padding 8
skinparam Nodesep 150
skinparam ArrowColor DarkSlateGray
hide methods
hide empty members
hide circle

rectangle "AI-Provider" <<external service>> {

}
rectangle "TopicExtractionProvider" <<external service>> {

}

rectangle "PLE domain diagram" {
  class "StudyRoom" {
    welcomeText
    name
    directLink
    settings
  }
  class Topic {
    topicNumber
    rating
  }
  class Conversation {
    threads
    aiAssistantContext
  }
  class "Learner" {
  }
  class "CoLearner" {
  }
  class "AI-Assistant" <<USP>> {
    name
    description
    behaviourInstructions
    shareRestrictions
    model
    modelProvider
    modelProperties
    files
  }
  class "TopicExtraction" {}

  "StudyRoom" -- "CoLearner"
  "CoLearner" <|-down- "Learner"
  "StudyRoom" *- Topic
  "StudyRoom" *- Conversation
  Conversation -.> "AI-Assistant" : <<use>>
  "StudyRoom" *- "AI-Assistant"
  Topic -o Conversation
  Conversation -.> "TopicExtraction" : <<uses>>
  "TopicExtraction" -.> "TopicExtractionProvider" : <<use>>
  "AI-Assistant" -.> "AI-Provider" : <<use>>
}

legend right
|<img:https://git.thm.de/arsnova/frag.jetzt/-/raw/staging/src/assets/icons/chat_bot_green.png{scale=0.4}> |= \n\n »frag.jetzt« — PLE mode |
| Domain glossary | [[https://git.thm.de/arsnova/frag.jetzt/-/raw/staging/docs/diagrams/Glossary.pdf]] |
| Production server | [[https://frag.jetzt]] |
| Repository | [[https://git.thm.de/arsnova/frag.jetzt/-/blob/staging/README.md]] |
| Staging server | [[https://staging.frag.jetzt]] |
| UML tool| PlantUML-Server Version 1.2023.12 - graphviz (20230911.1827)|
| Authors| Ruben Bimberg, Klaus Quibeldey-Cirkel, Sascha San Juan|
| Contact| [[mailto:ruben.bimberg@mni.thm.de]] |
| Last revision| 23.12.2024 |
end legend
@enduml
