@startuml

scale 1.0

left to right direction

skinparam backgroundColor Linen
skinparam LegendBackgroundColor Strategy
skinparam LegendBorderThickness 0
skinparam LegendFontSize 20
skinparam Padding 5
skinparam defaultFontSize 24
skinparam Nodesep 100
skinparam ArrowThickness 2
skinparam shadowing true

skinparam usecase {
    BackgroundColor PaleGreen
    BorderColor Green
    BackgroundColor<<USP>> Pink
    BorderColor<<USP>> HotPink
    BorderThickness 2
    ArrowThickness 2
    ArrowColor Green
    ActorBorderColor Green
}

actor Lecturer
actor Student
actor Moderator

note "If a lecturer is registered and logs in with her account, \nher sessions remain stored for 180 days after the last visit, \notherwise they are deleted when she logs out." as NoteForCreateSession
note "Registered students can receive a bonus \nfor particularly interesting questions." as NoteForJoinSession

rectangle "frag.jetzt | use-case diagram \n" << Business >> {

    (Join session) --- NoteForJoinSession
    (Create session) --- NoteForCreateSession

    Lecturer -- (Create session)
    (Evaluate questions) <.. (Delete question) : << extend >>
    Student-- (Join session)
    Moderator ---- (Moderate questions)
    (Create session) <.. (Export questions) : << extend >>
    (Create session) <.. (Assign moderator to session) : << extend >>
    (Create session) <.. (Ask question) : << extend >>
    (Create session) <.. (Evaluate questions) : << extend >>
    (Moderate questions) <.. (Ban question) : << extend >>
    (Evaluate questions) <.. (Ban question) : << extend >>
    (Join session) <.. (Ask question) : << extend >>
    (Join session) <.. (Vote up question) : << extend >>
    (Join session) <.. (Vote down question) : << extend >>
    Lecturer - (Interact with dashboard)
    Moderator - (Interact with dashboard)
    Student - (Interact with dashboard)
}

legend right
  |<img:https://git.thm.de/arsnova/arsnova-lite/raw/staging/src/assets/icons/Logo_frag_jetzt_128x128.png> |= \n\n »frag.jetzt« |
  | Produktion | [[https://frag.jetzt]] |
  | Repository | [[https://git.thm.de/arsnova/frag.jetzt]] |
  | Staging Server | [[https://staging.frag.jetzt]] |
  | UML-Tool| PlantUML v1.2019.5|
  | Ersteller| Klaus Quibeldey-Cirkel|
  | Mail| klaus.quibeldey-cirkel@mni.thm.de |
  | Letzte Änderung| 26.08.2019 |
end legend

@enduml

