// all spaces gets replaced with \s* (multiple or none whitespaces)
// all words are case insensitive
export const stopWords = [
  'Frage',
  'Fragen',
  'Antwort',
  'Aufgabe',
  'Hallo',
  'Test',
  'bzw',
  'bzw.',
  'muss',
  'mal',
  'zb.',
  'zb',
  'z. b.',
  'Zum Beispiel',
  'Beispiel',
  'Bsp',
  'jede',
  'jeder',
  'jede/r',
  'bisschen',
  'bißchen',
  'okay',
  'ok',
  'o.k.',
  'Mir',
  'Sorry',
  'Was',
  'Warum',
  'Inwiefern',
  'Klick',
  'Anzahl',
  'Erzählt',
  'Reicht',
  'Möglichkeit',
  'Nenne',
  'Siehst du',
  'Du musst',
  'Das heißt',
  'Denkst du',
  'Kannst du',
  'Könntest du',
  'Nochmal',
  'Teste',
  'Falls',
  'Nächstes',
  'Gib',
  'Guten Tag',
  'Moin',
  'Satz',
  'Question',
  'uns',
  'liest'
];
export const superfluousSpecialCharacters = '“”‘’„‚«»‹›『』﹃﹄「」﹁﹂",《》〈〉\'`#&…\\';
