version: '3.7'

services:

  analysis:
    image: localhost/sonarscanner-cli
    build:
      context: ..
      dockerfile: analysis/Dockerfile
    working_dir: /frag
    entrypoint: /frag/analysis/entrypoint.sh
    depends_on:
      - sonarqube
    networks:
      - sonar
    volumes:
      - ..:/frag

  sonarqube:
    image: sonarqube:7.9.1-community
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    ports:
      - '9000:9000'
    networks:
      - sonar
    volumes:
      - sonar_data:/opt/sonarqube/data

networks:
  sonar:

volumes:
  sonar_data:
